name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  http: ^0.12.0+2
  uuid: ^2.2.2
  args: ^1.5.2
  flutter_bloc: ^3.2.0
  equatable: ^1.2.2