[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
ferris-says = "0.3.1"
libsql = "0.3.5"
tokio = { version = "1.37.0", features = ["full"] }
